# Generated by Django 3.0.2 on 2020-01-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('marca', models.TextField()),
                ('preco', models.FloatField()),
                ('status', models.BooleanField(default=1)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
